extern const GeoLayout testmap_area_1_geo[];
extern const GeoLayout testmap_area_1[];
extern const Collision testmap_area_1_collision[];
extern const MacroObject testmap_area_1_macro_objs[];
extern u8 testmap_dl_bob_textures_05800_rgba16_ci8[];
extern u8 testmap_dl_bob_textures_05800_rgba16_pal_rgba16[];
extern u8 testmap_dl_bob_textures_0A000_rgba16_ci8[];
extern u8 testmap_dl_bob_textures_0A000_rgba16_pal_rgba16[];
extern Vtx testmap_dl_deathplane_mesh_layer_5_vtx_cull[8];
extern Vtx testmap_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx testmap_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx testmap_dl_Ground_mesh_layer_1_vtx_cull[8];
extern Vtx testmap_dl_Ground_mesh_layer_1_vtx_0[327];
extern Gfx testmap_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx testmap_dl_Ground_mesh_layer_1_vtx_1[145];
extern Gfx testmap_dl_Ground_mesh_layer_1_tri_1[];
extern Gfx mat_testmap_dl_f3dlite_material[];
extern Gfx mat_revert_testmap_dl_f3dlite_material[];
extern Gfx mat_testmap_dl_ground[];
extern Gfx mat_revert_testmap_dl_ground[];
extern Gfx mat_testmap_dl_f3dlite_material_001[];
extern Gfx mat_revert_testmap_dl_f3dlite_material_001[];
extern Gfx testmap_dl_deathplane_mesh_layer_5[];
extern Gfx testmap_dl_Ground_mesh_layer_1[];
